cd core && npm run build && cd ..
cd ui && npm run build && cd ..
cd webserver && npm run build && cd ..
cd examples && npm run build && cd ..
cd rx && npm run build && cd ..
cd rxui && npm run build && cd ..
cd rxreact && npm run build && cd ..
cd citifakebank/server && npm run build && cd ../..
cd citifakebank/ui && npm run build && cd ../..
cd userprofile-example/server && npm run build && cd ../..
cd userprofile-example/ui && npm run build && cd ../..
