FROM node:16
# ENV NODE_ENV=production
ENV PORT 3001
WORKDIR /blueprint
COPY . .
RUN make install
RUN make build 
RUN cd webserver
EXPOSE 3000
CMD ["npm", "--prefix", "./webserver", "run", "examples/citifakebank"]
