FROM node:16
# ENV NODE_ENV=production
ENV PORT 3000
WORKDIR /blueprint
COPY . .
RUN make install-core
RUN make build-core
RUN cd examples/userManagement && make install && make build && cd ..;
EXPOSE 3000
CMD cd examples/userManagement; make run-ui-prod;
