FROM node:16
# ENV NODE_ENV=production
ENV PORT 3001
ENV HOST 0.0.0.0
WORKDIR /blueprint
COPY . .
RUN make install
RUN make build 
RUN cd webserver
EXPOSE 3001
CMD ["npm", "run", "--prefix", "./webserver", "examples/citifakebank-blueprint"]
