cd core && npm publish && cd ..
cd ui && npm publish && cd ..
cd webserver && npm publish && cd ..
cd examples && npm publish && cd ..
cd rx && npm publish && cd ..
cd rxui && npm publish && cd ..
cd rxreact && npm publish && cd ..
cd citifakebank/server && npm publish && cd ../..
cd citifakebank/ui && npm publish && cd ../..