cd server && npm install && cd ..
cd clients && make install && cd ..
cd diagram && npm install && cd ..
cd examples/userprofile && make install && cd ../..
cd examples/citifakebank && make install && cd ../..
cd templates/helloWorld && make install && cd ../..
cd templates/skeleton && make install && cd ../..
cd templates/userProfile && make install && cd ../..
cd templates/rectangle && make install && cd ../..
