cd server && npm publish && cd ..
cd clients && make publish && cd ..
cd create-blueprint-app && make publish && cd ..
cd examples/citifakebank && make publish && cd ../..
cd examples/userManagement && make publish && cd ../..
cd examples/userprofile && make publish && cd ../..
cd examples/rectangle && make publish && cd ../..
cd templates/helloWorld && make publish && cd ../..
cd templates/skeleton && make publish && cd ../..
cd templates/userProfile && make publish && cd ../..
cd templates/rectangle && make publish && cd ../..
cd templates/gettingStarted && make publish && cd ../..