name: Deploy
run-name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: auth
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/135708369468/locations/global/workloadIdentityPools/github-actions-pool-2/providers/github-actions-provider-2'
          service_account: 'github-actions@blueprint-8675309.iam.gserviceaccount.com'
      - run: make docker-authenticate
      - run: make install
      - run: make build
      - run: make test
      - run: make deploy-citifakebank
      - run: make deploy-citifakebank-blueprint